### ISSUE TITLE
can't npm install prosemirror

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#1]
This is because the npm package is just a stub for the moment.

What's the best way to build the website? Checking out `prosemirror` manually into `node_modules/`, and building the source inside that folder?

**Comment by marijnh** [comment]
The current npm package is just there to make sure no one else squats the package name. Specify a direct [git URL](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in your `package.json`. (I'm not going to bother putting versions on things until there is some slight stability.)

**Comment by ericandrewlewis** [comment]
Gotcha. Mind if I add some install docs to the README for running the website locally?
