### ISSUE TITLE
Please redirect from http to https on main site

### ISSUE THREAD

**Issue by stgolem** [ProseMirror/website#102]
Currently everywhere i see main site as http://prosemirror.net but browsers don't like plain http any more. I suggest you to redirect from http to https version by default. And replace all visible links here on github repos.

**Comment by marijnh** [comment]
Done (though do comment if you find a link I missed)

**Comment by stgolem** [comment]
It is left on the main github account page: https://github.com/ProseMirror

**Comment by marijnh** [comment]
Fixed.
