### ISSUE TITLE
Unexpected text insertion in linting example

### ISSUE THREAD

**Issue by MarkWilliams3141** [ProseMirror/website#104]
Placing the cursor after comma linting decoration and triggering deleting several times causes unexpected text insertion. See gif below:

![https://imgur.com/0b047373-c47e-4bae-94ff-c4fae621a26f](https://i.imgur.com/WWMgbdk.giff)

This was tested on Chrome version 80

**Comment by marijnh** [comment]
I think this was another symptom of https://github.com/ProseMirror/prosemirror/issues/1044 . After rebuilding the demo with the current code, it is gone.
