### ISSUE TITLE
Collaborative Editing not working

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#11]
When adding text on [the collab example](http://prosemirror.net/demo_collab.html#edit-Example), I see a note that says

<img width="502" alt="screen shot 2016-01-06 at 7 23 27 pm" src="https://cloud.githubusercontent.com/assets/1087646/12158773/1e9af8d4-b4ab-11e5-8f18-c8050e20a2bc.png">

**Comment by ericandrewlewis** [comment]
#12 follows some API changes, but I can't figure out why the Events API endpoints return 500s.

**Comment by marijnh** [comment]
I rebuilt and reset the collab server, and things seem to work. It was running rather old code. Are you getting the same errors locally? Could it be that your `demo-instances.json` is old (in a previous format)? Try removing it and restarting.

**Comment by ericandrewlewis** [comment]
What's the best way to run this example locally?

**Comment by marijnh** [comment]
You have to access it through a webserver, and then proxy traffic to docs/ to the server started with `npm start`. Here's the nginx config that I'm using:

```
server {
	server_name pm;
        listen 80;

	root /home/marijn/src/prosemirror-website/public/;

	location /docs/ {
           proxy_pass http://localhost:8000/;
	   proxy_read_timeout 6m;
	   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

**Comment by ericandrewlewis** [comment]
Since things are working now, I'm going to close this out. 

I hope to follow-up at some point with instructions on setting this up locally.

**Comment by ericandrewlewis** [comment]
I ended up writing a node server to serve static assets and proxy to the document server to get this running locally without an nginx dependency. It requires installing an extra node module `http-proxy`. You can place this in `public/index.js`:

```javascript
var http = require("http"),
    url = require("url"),
    path = require("path"),
    fs = require("fs")
    port = process.argv[2] || 8080;

var proxy = require('http-proxy').createProxyServer({});
proxy.on('error', function(err, req, res) {
	res.end();
})
http.createServer(function(request, response) {

  var uri = url.parse(request.url).pathname
    , filename = path.join(process.cwd(), uri);
	if ( uri.indexOf('/docs/') === 0 ) {
		uri = uri.replace('/docs', '');
		request.url = request.url.replace('/docs', '');
		proxy.web(request, response, { target: 'http://localhost:8000' });
	} else {
		fs.exists(filename, function(exists) {
	    if(!exists) {
	      response.writeHead(404, {"Content-Type": "text/plain"});
	      response.write("404 Not Found\n");
	      response.end();
	      return;
	    }

	    if (fs.statSync(filename).isDirectory()) filename += '/index.html';

	    fs.readFile(filename, "binary", function(err, file) {
	      if(err) {
	        response.writeHead(500, {"Content-Type": "text/plain"});
	        response.write(err + "\n");
	        response.end();
	        return;
	      }

	      response.writeHead(200);
	      response.write(file, "binary");
	      response.end();
	    });
	  });
	}

}).listen(parseInt(port, 10));

console.log("Static file server running at\n  => http://localhost:" + port + "/\nCTRL + C to shutdown");
````

then run `node public/index.js` and also `npm run start`.
