### ISSUE TITLE
make is failing

### ISSUE THREAD

**Issue by MateMahinKhan** [ProseMirror/website#138]
Hey folks, thanks for the lovely text editor. 

I'm trying to run the website on windows but make command is failing. I had to download GnuWin32 for it to run on windows 10.
```
Access denied - PAGES
File not found - -NAME
Access denied - PAGES
File not found - -NAME
-d was unexpected at this time.
mkdir -p public/examples/basic/
The syntax of the command is incorrect.
make: *** [Makefile:44: public/examples/basic/example.js] Error 1
```

It looks the folder/files might be readonly but I double checked for permission. Ran as administrator as well.

Is there a possibility of something else that I didn't do right?

**Comment by marijnh** [comment]
I don't think anyone has tried building on windows before, the makefile is likely full of unix-isms. I'm not sure how well GnuWin32 covers those. The `-NAME` error seems to come from `find -name`, for example. Definitely not a permission issue.

**Comment by MateMahinKhan** [comment]
I'll post steps here if successful

**Comment by MateMahinKhan** [comment]
There is a ubuntu terminal available in windows 10. It does include the make command.

**Comment by MateMahinKhan** [comment]
I can create a note for windows on readme file and open a pull request if you think that'll be helpful?
