### ISSUE TITLE
Error: Missing or invalid metainfo on pages/examples/basic/index.md

### ISSUE THREAD

**Issue by MateMahinKhan** [ProseMirror/website#140]
When I run the `make` command it throws an error after this line because `meta` is `null`.
`var meta = /^!(\{[^]*?\})\n\n/.exec(text)`

```
exports.buildFile = function(file) {
  var text = fs.readFileSync(file, "utf8"), result
  if (/\.md$/.test(file)) {
    var meta = /^!(\{[^]*?\})\n\n/.exec(text)
    if (!meta) throw new Error("Missing or invalid metainfo on " + file)
    var data = JSON.parse(meta[1])
    data.content = text.slice(meta[0].length)
    data.fileName = file
    result = mold.defs[data.template](data)
  } else {
    result = mold.bake(file, text)()
  }
  return result
}
```

**Comment by marijnh** [comment]
Did you check out the repository with `\r\n` line endings? That would break this match. But you can set up git to not do that—I think `git config core.autocrlf input` does this (but I'm not sure).

**Comment by MateMahinKhan** [comment]
`git config --get core.autocrlf` results in `input` 
I'll look into it.

**Comment by marijnh** [comment]
Doing the entire git checkout inside the ubuntu subsystem might work (though, again, I don't have any direct experience with this stuff)

**Comment by MateMahinKhan** [comment]
That worked! Thanks a lot!
