### ISSUE TITLE
Discussion forum is not loading

### ISSUE THREAD

**Issue by rosslh** [ProseMirror/website#142]
When I go to any page in [discuss.prosemirror.net](https://discuss.prosemirror.net), all I see is a blank page. 

In the console, I see the error `Uncaught ReferenceError: Discourse is not defined`. I am getting this error in Chrome 88.0.4324.150 and Firefox 85.0.2.

Example URLs where this issue is encountered:

- https://discuss.prosemirror.net/
- https://discuss.prosemirror.net/t/how-easy-prosemirror-to-set-up-and-use/3170

For anyone else encountering this, using Google's cache (in the dropdown next to the search result) is a decent work-around if you just want to read the content.

**Comment by marijnh** [comment]
Strange. When I open it in a browser where I'm logged into the forum it works, but in a private window I also get the empty page. I'll try to look into this tomorrow.

**Comment by marijnh** [comment]
Appears to have been some webserver config thing. Should be better now.

**Comment by rosslh** [comment]
> Appears to have been some webserver config thing. Should be better now.

Thanks for the quick resolution and for this great editor!
