### ISSUE TITLE
[Question] it seems that prosemirror-history do not support `preserveItems` config?

### ISSUE THREAD

**Issue by lastnigtic** [ProseMirror/website#144]
I am reading the example code of collaborative editing and have questions about the following lines.

https://github.com/ProseMirror/website/blob/12d0391769a9fcfe938218fabd621e38ebc77839/src/collab/client/collab.js#L48

It seems to be replaced by `pluing.sepc.historyPreserveItems`?

**Comment by marijnh** [comment]
Yes, that indeed seems to be a holdover from an old interface. Removed in 1b2cc4f
