### ISSUE TITLE
Editing footnotes example 'Mark' glitches

### ISSUE THREAD

**Issue by jvissers** [ProseMirror/website#148]
The _editing footnotes_ example shows (italic) Marks when you are entering into the first footnote. At that time also the italic button is enabled (for the whole footnote text that is displayed). It seems to suggest that the Mark controls (e.g. bold, italic) are usable in the footnote, however there are some problems with that. The biggest issue is that pressing a Mark control while the footnote text has focus - will set the Mark for the whole footnote text. This makes me wonder whether this is intentional because when moving into the first footnote of the example, there are just a few isolated words that carry the Mark.

**Comment by catdevnull** [comment]
This still happens and it would be great if it didn't happen :)

**Comment by marijnh** [comment]
The outer editor has the selection on the entire footnote node, so pressing the buttons on that editor will affect that selection. Add custom controls or keybindings for your inner editor if you want people to be able to act on that selection (or wire up the outer controls to be smart about which editor is focused, I guess).

I don't want to further complicate the example.
