### ISSUE TITLE
Unintended behavior within the Codemirror6 demo

### ISSUE THREAD

**Issue by bvanjoi** [ProseMirror/website#157]
When I pressed backspace, I actually deleted two chars, and I had similar behavior when I press space.

https://user-images.githubusercontent.com/30187863/179883974-54d881ac-141d-4d4b-b148-addc73b7be00.mov

**Comment by marijnh** [comment]
[This patch](https://github.com/ProseMirror/website/commit/a7a91ccf5cf7bf1d202cd1be39b4a70d4a9060e6) should help.
