### ISSUE TITLE
ProseMirror website embedded CodeMirror example docs does not match the markdown file

### ISSUE THREAD

**Issue by fletchertyler914** [ProseMirror/website#158]
I left a detailed comment on the commit that fixed my issue, but long story short, the website is not reflecting the markdown from the master branch.

See comment here:
https://github.com/ProseMirror/website/commit/a7a91ccf5cf7bf1d202cd1be39b4a70d4a9060e6#commitcomment-80339310

Hopefully this can save some headache for those copying and pasting from the ProseMirror site!

**Comment by marijnh** [comment]
Looks like the build process failed to notice it had to update that file. I've triggered a manual rebuild.
