### ISSUE TITLE
Extending schema

### ISSUE THREAD

**Issue by snnsnn** [ProseMirror/website#159]
Hi, I was wondering if this statement is accurate? It is taken from 
https://github.com/ProseMirror/website/blob/master/markdown/guide/schema.md.

> Such maps support a number of methods to conveniently create updated versions. For example you could say schema.markSpec.remove("blockquote") to derive a set of nodes without the blockquote node, which can then be passed as the nodes field for a new schema.

The reason why I ask is when I log the schema, I don't see any `markSpeck` property.

```javascript
const s1 = new Schema({
  nodes: {
    doc: { content: '(paragraph | h1)+' },
    paragraph: {
      content: 'text*',
      toDOM: () => ['p', 0],
      parseDOM: [{ tag: 'p' }],
    },
    h1: {
      content: 'text*',
      toDOM: () => ['h1', 0],
      parseDOM: [{ tag: 'h1' }],
    },
    text: {},
  },
});

console.log(s1);
```

If it is accurate then, please can you provide an example. Thank you.

**Comment by marijnh** [comment]
That's a remnant of and old interface that was changed a long time ago. Attached patch fixes it.
