### ISSUE TITLE
footnote example allows footnote inside footnotes

### ISSUE THREAD

**Issue by catdevnull** [ProseMirror/website#160]
I'm bringing this up because it breaks the editor (as it relies on the assumption that that doesn't happen) and there's no obvious way to solve it (it's not possible to change the schema of the inner editor.) What can be done?

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch seems like a rather obvious way to solve it.

**Comment by catdevnull** [comment]
That's a way, in our implementation we want to allow `block+` which is not possible with this approach. Any clue on how to solve it in our case?

**Comment by marijnh** [comment]
You could define different versions of your block nodes that have more limited content.
