### ISSUE TITLE
Hi, examples don't work

### ISSUE THREAD

**Issue by scriptype** [ProseMirror/website#161]
I'm trying to reach any visuals to finally understand what kind of a UI/UX is offered by ProseMirror.

However, all the examples on the website are broken due to https://prosemirror.net/examples/prosemirror.js being empty.

It causes the example codes to fail, as each example injects `PM` to a module that is the example code.

**Comment by scriptype** [comment]
Note that, this apparently also means that examples on the internet that relied on that url also has stopped working probably ever since https://github.com/ProseMirror/website/commit/1b6d6b377e3e30c4bfe368ec1576b1a529364eb7

For example: https://codepen.io/JessieWooten/pen/wYObEX

**Comment by marijnh** [comment]
Website build process was broken. It should be back to normal now.
