### ISSUE TITLE
Someone should fix this

### ISSUE THREAD

**Issue by scriptype** [ProseMirror/website#162]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/5516876/213259184-dbc0453c-9c60-4426-b76c-7b8422cc4a3d.png">

**Comment by marijnh** [comment]
Have you considered including some information that might help here? Such as which browser you're using, and whether there are any errors in your dev console.

**Comment by scriptype** [comment]
Oh, I see, once the examples got fixed, an example appeared there in the header section, pushing the content down.

> Have you considered including some information that might help here? Such as which browser you're using, and whether there are any errors in your dev console.

Yeah, I did. I'm using Firefox. I tried opening the page in Chrome and then incognito Chrome to verify that it's not my browser extensions causing a problem. So, once it's clear that the webpage is like that out in the wild, for me the issue was very clear from the issue title and description. You just needed to assume I did the checks on my side ✌️
