### ISSUE TITLE
inconsistency between Schema constructor's argument type &  SchemaSpec interface?

### ISSUE THREAD

**Issue by GUGIG** [ProseMirror/website#163]
In /docs/ref/#model.Schema.spec, the `Schema`'s argument `spec` has three properties -
(1) `nodes`, (2) `marks`, (3) `topNode`

and the property `marks` doesn't seem optional (no question mark after property name).

<img width="299" alt="image" src="https://user-images.githubusercontent.com/16061038/217998652-86d8fdca-53ac-4971-a927-e1af13df849f.png">

but in /docs/ref/#model.SchemaSpec, it describes the `SchemaSpec` interface (which is the type of `spec` parameter above)
where the `marks` property is optional.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/16061038/217998599-c59d9ff8-d42e-4690-bba5-07f96bdf5d94.png">

```typescript
const schema = new Schema({nodes: {doc: {content: 'text*'}, text: {}}}) // no marks
const state = EditorState.create({schema})
const view = new EditorView(document.querySelector('#editor'), {state})
```
when i tried making an example editor w/ a simple schema without providing `marks` property it seemed to work,
so I think the reference document regarding`spec` parameter of `Schema` constructor should have it's `marks` property as optional.

**Comment by marijnh** [comment]
The docs you are looking at describe what the `spec` property of `Schema` looks like. That one always has a `marks` property (and it is always an `OrderedSet`. The constructor is described as taking an argument of type `SchemaSpec<Nodes>` which the docs in the second screenshot correctly define as having an _optional_ marks property.

**Comment by GUGIG** [comment]
Oh it's a property type🤦‍♂️
Thank you for answering!
