### ISSUE TITLE
Error with the Makefile

### ISSUE THREAD

**Issue by jesus-pacto** [ProseMirror/website#164]
When I run the command `make` after install the dependencies, I receive this error:

````
node bin/build-library.js > public/examples/prosemirror.js
cat node_modules/prosemirror-view/style/prosemirror.css node_modules/prosemirror-menu/style/menu.css node_modules/prosemirror-gapcursor/style/gapcursor.css node_modules/prosemirror-example-setup/style/style.css public/css/editor-base.css > public/css/editor.css
cp node_modules/codemirror/lib/codemirror.css public/css/codemirror.css
cp: cannot stat 'node_modules/codemirror/lib/codemirror.css': No such file or directory
make: *** [Makefile:53: public/css/codemirror.css] Error 1
````

Even though I can still start the server but then the editor do not render.

**Comment by marijnh** [comment]
That was a leftover from the old CodeMirror version. Removed by https://github.com/ProseMirror/website/commit/3072588803b59485fcd2f887790a1ecf25230d40 . I am still trying to figure out why my own build process didn't break on that error.
