### ISSUE TITLE
Guide - document nodes description incorrect ?

### ISSUE THREAD

**Issue by tonyhallett** [ProseMirror/website#166]
> So a ProseMirror document is a tree of block nodes, with most of the leaf nodes being textblocks, which are block nodes that contain text.

Should it be -  document is a tree of nodes, with most leaf nodes being text nodes, which are inline nodes that contain text ?

Given a normal schema https://github.com/ProseMirror/prosemirror-schema-basic/blob/master/src/schema-basic.ts
with content `<p>A paragraph</p>`

Iterating the doc
<img width="171" alt="image" src="https://github.com/ProseMirror/website/assets/11292998/00b0d4ea-9770-46ab-bc1e-d646ed1b37e2">

**Comment by marijnh** [comment]
This is describing the block structure, so though technically the inline nodes are also part of the tree, and often form the leaves, for the thing that it is talking about, it is correct.
