### ISSUE TITLE
All or most of the External links to be fixed to open in new tabs

### ISSUE THREAD

**Issue by tmsagarofficial** [ProseMirror/website#167]
I want to point out that most or all of the external links in the website open in the tab, the same as the current tab causing hindrance to the user experience. the user ahs to come back to the page and go again for every external link they wan to access..

Pls assign me this issue so that I can work on this.

My solution: I Would like to use target=_blank to achieve the solution for this. I'm open for discussion

**Comment by marijnh** [comment]
Browsers allow you to open links in a new tab (via the context menu, middle-click, or holding control). I feel that is enough.
