### ISSUE TITLE
public/css/editor.css missing

### ISSUE THREAD

**Issue by ile** [ProseMirror/website#168]
Trying to run the collab demo is interrupted when the file `/editor.css` is not found. It should be in `public/css/editor.css`.

![image](https://github.com/ProseMirror/website/assets/433707/fa582e11-38a9-4c8d-8a15-bdb12868030d)

Adding that file from the https://prosemirror.net/ website will help and get the demo to run.

**Comment by marijnh** [comment]
That's build by [this rule](https://github.com/ProseMirror/website/blob/master/Makefile#L45).

**Comment by ile** [comment]
Oh, ok, sorry, should have read the README more carefully.
