### ISSUE TITLE
The collab example's comments are slightly broken

### ISSUE THREAD

**Issue by imh** [ProseMirror/website#169]
**Steps to reproduce:**

1. Write some text in the editor
2. Add a comment to part of it
3. Select the commented text
4. Click and drag it elsewhere

**Expected behavior:** I expect the comment to move with the text. It stays with the text when all other types of edits are performed, as far as I can tell. All other types of attributes stay with text when moved as well, as far as I can tell.

**Observed behavior:** The comment disappears.

**Browser:** Chrome version 119.0.6045.199 (Official Build) (arm64)

**Comment by marijnh** [comment]
That feature is out of scope for this demo.
