### ISSUE TITLE
The reference documentation is not clear about nullable types

### ISSUE THREAD

**Issue by stof** [ProseMirror/website#170]
For instance, https://prosemirror.net/docs/ref/#state.TextSelection shows `$cursor: ResolvedPos` and then the description says it can be `null`.

It would be much better to show it as ` $cursor: ResolvedPos|null`

**Comment by stof** [comment]
It can definitely be `null`:
https://github.com/ProseMirror/prosemirror-state/blob/88e2a24104481098f0f660e74240c0f846e7fd6e/src/selection.ts#L237-L239

**Comment by marijnh** [comment]
Oh right, that one _is_ nullable. That is some kind of issue in the documentation builder. It emits the right types locally, weirdly. Investigating.

**Comment by marijnh** [comment]
Okay, I found the issue. The wrong tsconfig was read by the build process, putting TypeScript in non-strict mode, causing it to drop types like this.
