### ISSUE TITLE
www.prosemirror.net displays CodeMirror's website

### ISSUE THREAD

**Issue by rijenkii** [ProseMirror/website#171]
See for yourself: https://prosemirror.net vs https://www.prosemirror.net.
![image](https://github.com/ProseMirror/website/assets/5338332/1caaa723-029a-4e48-a12d-857c576b64fe)

**Comment by marijnh** [comment]
Should be better now (though your browser may still be holding on to the old permanent redirect).

**Comment by rijenkii** [comment]
Certificate does not cover the `www` subdomain:
```
$ curl https://www.prosemirror.net/
curl: (60) SSL: no alternative certificate subject name matches target host name 'www.prosemirror.net'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
![image](https://github.com/ProseMirror/website/assets/5338332/339b9bac-d306-41b1-a4ba-7bb3afe087de)

**Comment by marijnh** [comment]
This is quite a bit of work for a subdomain that isn't actually used, but okay, I've regenerated the certificate.
