### ISSUE TITLE
Best Practice Example for Accessibility

### ISSUE THREAD

**Issue by mgifford** [ProseMirror/website#175]
A great deal of $$ is spent tracing down accessibility issues after they have gotten into the code of a website. For some reason, people assume that authors will know and practice writing accessible content. They don't.  

A11yFirst is a good example of how a WYSIWYG can cut down the costs of delivering content by providing better support to authors.  ProseMirror introduces more authors, so this is even more important.   
  
[https://a11yfirst.web.illinois.edu/](https://a11yfirst.web.illinois.edu/)

Their demo is here:

[https://a11yfirst.gitlab.io/custom/a11yfirst.html](https://a11yfirst.gitlab.io/custom/a11yfirst.html)

Headings are a huge problem. Most CMS shouldn't allow a user to add an H1. Starting with H2, one shouldn't allow skipped headings.

Maybe ProseMirror has the capacity to have a UI like this, but would be nice to see a demo of it.

**Comment by marijnh** [comment]
This kind of thing is outside of the scope of the library and outside my expertise. It'd be great if someone publishes a resource like this, but it's not going to happen under the project's umbrella.
