### ISSUE TITLE
Add a schema guide

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/website#20]
Containing example code snippets for a few types of nodes, and describing the way a schema's structure works.

**Comment by will-hart** [comment]
I can make an attempt at this one.

**Comment by will-hart** [comment]
Initial draft [here][1] for feedback on style/content/general accuracy. 

Not so interested in grammar / formatting suggestions yet. I know there are formatting issues and I don't think the markdown parsing works yet as not all the block types are handled... 

P.S. I wrote this in a ProseMIrror editor which I think is very meta :) 

[1]: https://github.com/will-hart/website/blob/schema_guide/pages/guide/schema.md

**Comment by marijnh** [comment]
Thanks! Some feedback:

 - Try to start with a description of the concepts (node types and marks) that make up a schema, and the way node nesting is constrained, so that readers get a better idea of what a schema is made of.

 - For superscript, I'd be more tempted to use a mark than a node. Maybe implement both a mark type and a node type?

**Comment by will-hart** [comment]
Thanks for the comments.

> description of the concepts (node types and marks) that make up a schema, and the way node nesting is constrained 

I have a very rudimentary understanding of this but I'll review the docs and code and have a go at a draft.

> use a mark rather than a node

Yes that probably makes more sense. I'll review.

**Comment by will-hart** [comment]
By the way, I'm going to be away from my computer for a couple of weeks so will update the draft after that.
