### ISSUE TITLE
Collab Editing Demo is broken

### ISSUE THREAD

**Issue by asteadman** [ProseMirror/website#24]
I'm seeing a red error message on the upper right corner of my screen on http://prosemirror.net/demo/collab.html#edit-Example.
> Error: Request failed: Bad Gateway
>
> 502 Bad Gateway

The console output is:
```
GET http://prosemirror.net/docs/Example 502 (Bad Gateway)
    req @ bundle_collab.js:580
    GET @ bundle_collab.js:591
    start @ bundle_collab.js:61
    connectFromHash @ bundle_collab.js:259
    1../comment @ bundle_collab.js:268
    s @ bundle_collab.js:1
    e @ bundle_collab.js:1
    (anonymous function) @ bundle_collab.js:1
```

**Comment by marijnh** [comment]
Seems to have crashed. I've restarted it, and set up logging to be able to debug the next crash.
