### ISSUE TITLE
Lint demo broken

### ISSUE THREAD

**Issue by maacl** [ProseMirror/website#26]
If I try to download the website and run the demos locally the lint demo throws the following error when hovering over the problems

    bundle_lint.js:13119 Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

If I download the bundle_lint.js from the live website and replace the one built from the git repo with that, everything works.

**Comment by marijnh** [comment]
Were you using an npm installed prosemirror? If so, the problem was probably that the version number in package.json was way out of date.

**Comment by maacl** [comment]
I was, so that might be the issue. Will try to verify later today.
