### ISSUE TITLE
Add a plugin guide

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#28]
We should create a guide on how to create a ProseMirror add-on. Suggestions welcome on what this should include.

**Comment by forresto** [comment]
Agreed. I usually learn something about JS by reading @marijnh's code, but a version of eg https://github.com/ProseMirror/website/blob/master/src/demo/lint.js with some hand-holding would be nice.

**Comment by marijnh** [comment]
I've been putting off the guide-writing until I finalize 1.0, since rewriting documentation after breaking changes isn't a lot of fun, but I agree, this should definitely be more clearly documented.

**Comment by marijnh** [comment]
Done in e3454f1fdd173
