### ISSUE TITLE
Install instructions break static files

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#30]
We now reference to static files with absolute URLs (e.g. `/site.js`), so opening `public/index.html` as we suggest in the README does not work.

Perhaps we could suggest running a local node server a la [http-server](https://github.com/indexzero/http-server), or include a small static files server in node.

**Comment by marijnh** [comment]
We could extend the collab demo server to also optionally serve `public` as static files. That'd also make it easier for people to set that up locally.

**Comment by marijnh** [comment]
I've removed that sentence from the README, and added a devserver that provides an easy way to set up a local server (including collaborative support) for testing.
