### ISSUE TITLE
Editing the website does not work anymore

### ISSUE THREAD

**Issue by padenot** [ProseMirror/website#36]
I had a look at the website today, and I saw the post-it note, saying "You can edit this", so I tried and it didn't work.

The js console says `TypeError: baseKeymap.lookup is not a function`.

Tested on Firefox Nightly (52) and Dev edition (51), current Chrome Release and Canary, the same error happens everywhere.

**Comment by marijnh** [comment]
Oh, right, that was in some code that was only run on Mac platforms, and which I hadn't ran locally in months. Fixed by [this patch](https://github.com/ProseMirror/prosemirror-commands/commit/662b2bd5034b725326d83c44464e7c1489bff8f4), and released as 0.11.2 of the prosemirror-commands package.
