### ISSUE TITLE
Make views accessible in JS console

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#42]
Previously the ProseMirror view was made available on `window.pm`. 

I find this useful when wanting to try out basic ProseMirror thingies. Maybe we can set the views accessible as `window.EditorView` or whatever would be proper?

I guess this would apply to the [demo](https://github.com/ProseMirror/prosemirror/tree/master/demo) as well if we decide to go ahead with this.

**Comment by marijnh** [comment]
That's fine -- the nesting and tracking demos seem to still set `window.view`. Want to submit a PR that does this for the others as well?
