### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by laszbalo** [ProseMirror/website#50]
Unless somebody is trying to hack my connection, it seems that the SSL certificate on prosemirror.net has been expired today. Is somebody else experiencing the same?

**Comment by laszbalo** [comment]
It seems working fine now.

**Comment by marijnh** [comment]
Certbot somehow generated a weird certificate that was valid much shorter than the ones it normally creates, and then didn't renew it. I've forced to renew, which produced a normal-looking certificate, and I'm hoping it was a one-time failure.
