### ISSUE TITLE
Build error on clean install

### ISSUE THREAD

**Issue by skue** [ProseMirror/website#54]
Looks like the build process expects CHANGELOG.md before it gets downloaded.

Steps to Reproduce
---
 1. `git pull` main prosemirror repo, `cd` into it, `yarn install` (fyi, demo there works great)
 2. `cd ./website`, `yarn install`, `make`

Results
---

```
$ make
mkdir -p public//
node src/build/build.js pages//backers.html
mkdir -p public//docs/changelog/
node src/build/build.js pages//docs/changelog/index.html
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/username/Development/Repos/prosemirror/website/src/build/../../markdown/../CHANGELOG.md'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at mold.defs.markdownFile (/Users/username/Development/Repos/prosemirror/website/src/build/templates.js:20:23)
    at Mold.dispatch (/Users/username/Development/Repos/prosemirror/website/node_modules/mold-template/mold.js:38:25)
    at eval (eval at evaluate (/Users/username/Development/Repos/prosemirror/website/node_modules/mold-template/mold.js:188:10), <anonymous>:9:12)
    at exports.buildFile (/Users/username/Development/Repos/prosemirror/website/src/build/buildfile.js:28:35)
    at /Users/username/Development/Repos/prosemirror/website/src/build/build.js:9:16
    at Array.forEach (native)
    at Object.<anonymous> (/Users/username/Development/Repos/prosemirror/website/src/build/build.js:8:23)
make: *** [public//docs/changelog/index.html] Error 1
```

Workaround
---
Manually downloaded CHANGELOG.md via the command in the Makefile:

`$ curl https://raw.githubusercontent.com/ProseMirror/prosemirror/master/CHANGELOG.md > CHANGELOG.md`

…then ran `make` again and worked fine.

Version
---
Current ProseMirror/website master (40f9dd7)
MacOS 10.12.3
$ node --version
v6.10.0
$ yarn --version
0.21.3

**Comment by marijnh** [comment]
That's odd. There's a rule in the makefile for downloading CHANGELOG.md, and it's declarated as a dependency for building the changelog page, so make should, as far as I understand it, download it when it's missing. It does so on my machine (Linux) if I delete it.

**Comment by skue** [comment]
Agreed. I'm definitely not an expert on make, but was surprise to see that CHANGELOG.md dependency and find no other reference to CHANGELOG.md outside of the Makefile when I did a `grep -r`.

Was just about to try again with a fresh git pull and `make -d` to see if it gave more info… but looks like there's an issue with the new prosemirror-test-builder package not matching its GitHub name (https://github.com/ProseMirror/test-builder/issues/1)

**Comment by marijnh** [comment]
Did fixing ProseMirror/prosemirror-test-builder#1 resolve this?

**Comment by skue** [comment]
No. Thanks for that fix, but I had pulled prosemirror prior to the test-builder change — probably should have included the parent prosemirror version in addition to prosemirror/website version, so that was clear. The naming issue only prevented me from starting clean to re-replicate the issue.

Think the problem might be that two different rules match the `public/docs/changelog/index.html`, and CHANGELOG.md is only listed as a dependency on one. Could explain why our different platforms resolve this differently.

```
21 | public/docs/changelog/index.html: pages/docs/changelog/index.html CHANGELOG.md templates/* src/build/*.js
...|
25 | public/%.html: pages/%.* templates/* src/build/*.js
```
If I add CHANGELOG.md as a dependency on line 25, it works great.

**Comment by skue** [comment]
If it's helpful, here's the output of `make -d` with a clean copy of the website repo, after running `yarn install`.

[make-d-output.txt](https://github.com/ProseMirror/website/files/859260/make-d-output.txt)

Note the double slashes in references to `public//docs/changelog/index.html`, etc. Wondering if that could contribute to not matching the implicit rule (and its dependencies) on our different platforms, I modified the first line of the Makefile as follows:

````diff
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-PAGES:=$(shell find pages/ -name "*.html") $(shell find pages/ -name "*.md")
+PAGES:=$(shell find pages -name "*.html") $(shell find pages -name "*.md")
````

With this change it also works, and here's the successful debug output:

[modified-make-d-output.txt](https://github.com/ProseMirror/website/files/859348/modified-make-d-output.txt)

**Comment by marijnh** [comment]
> Think the problem might be that two different rules match

Oh, right, I had assumed the first would take precedence in that case, but I actually have no idea how make handles that. There's something in [the manual](https://www.gnu.org/software/make/manual/html_node/Multiple-Rules.html) but that doesn't seem to match the behavior you're seeing here at all.

**Comment by marijnh** [comment]
Attached patch declares this dependency in a cleaner way, but I don't know whether it'll help

**Comment by skue** [comment]
Unfortunately that doesn't help, same error. The problem seems to be with the extra slashes in the path — if I make this change:

````diff
- public/docs/changelog/index.html: CHANGELOG.md
+ public//docs/changelog/index.html: CHANGELOG.md
````

… then it works., just as if I remove the trailing slash in the `find` command on line 1 of the Makefile (see above, https://github.com/ProseMirror/website/issues/54#issuecomment-288185264).

Believe the culprit is that `find` command rather than `make`. Macs use BSD `find`, which cares whether the search directory ends in a trailing slash:

```
$ find pages/ -name "*.html"
pages//backers.html
pages//docs/changelog/index.html
pages//docs/index.html
pages//docs/ref/index.html
pages//examples/basic/index.html
pages//examples/codemirror/index.html
pages//examples/collab/index.html
pages//examples/dino/index.html
pages//examples/footnote/index.html
pages//examples/index.html
pages//examples/lint/index.html
pages//examples/markdown/index.html
pages//examples/track/index.html
pages//index.html
```

Per this [StackOverflow answer](http://apple.stackexchange.com/a/254224), those duplicate slashes are probably different than what you see on Linux with GNU `find` (?), and this apparently causes the Makefile rule to not match.

**Comment by marijnh** [comment]
Oh, I see. Does `find pages -name "*.html"` (without the slash after `pages`) produce a list without double slashes?

**Comment by skue** [comment]
That's right. Removing the trailing slashes in line 1 of the Makefile should fix this for Macs.

```
$ find pages -name "*.html"
pages/backers.html
pages/docs/changelog/index.html
pages/docs/index.html
pages/docs/ref/index.html
pages/examples/basic/index.html
pages/examples/codemirror/index.html
pages/examples/collab/index.html
pages/examples/dino/index.html
pages/examples/footnote/index.html
pages/examples/index.html
pages/examples/lint/index.html
pages/examples/markdown/index.html
pages/examples/track/index.html
pages/index.html
```

Thanks!!!

**Comment by marijnh** [comment]
Thanks for looking into that. See attached patch.
