### ISSUE TITLE
Changelog page contains wrong closing tags

### ISSUE THREAD

**Issue by marcelkorpel** [ProseMirror/website#55]
When viewing the HTML source for the [Changelog page](http://prosemirror.net/docs/changelog/) I noticed that the closing tags of all header elements are decremented by 1, e.g.

    <h4>Bug fixes</h3>

I think this is due to a wrong setting [here](https://github.com/ProseMirror/website/blob/master/pages/docs/changelog/index.html).

BTW, the `viewport` meta element is declared twice.

**Comment by marijnh** [comment]
Thanks for noticing. One of my markdown-processing kludges wasn't implemented very well.
