### ISSUE TITLE
Building and running website results in errors

### ISSUE THREAD

**Issue by marcelkorpel** [ProseMirror/website#64]
When following the instructions in the README and trying to build a local copy of the website using `make`, the process errors outputting:

    Error: ENOENT: no such file or directory, open '/zpool/home/mk/prosemirror/website/src/build/../../node_modules/prosemirror-gapcursor/src/README.md'

As `prosemirror-gapcursor` is not included in the dependencies, it isn't installed. After inserting

    "prosemirror-gapcursor": "^0.22.1",

in `package.json` (and issuing `npm install` again, of course) building the website finishes succesfully. However, running

    npm run devserver -- --port 8888

results in not being able to open any of the examples, causing errors like

    Error: ENOENT: no such file or directory, open '/zpool/home/mk/prosemirror/website/src/../pages/examples/basic/index.html'

Indeed, the `index.html` files are not generated.

**Comment by marijnh** [comment]
I'm working on the website at the moment, I'll have everything building again when I make the next release.

**Comment by marijnh** [comment]
The website appears to build again, now, and the dev server should also work

**Comment by marcelkorpel** [comment]
Thanks, but did you forget to push your changes?

**Comment by marijnh** [comment]
No, they are linked right there above my comment.

**Comment by marcelkorpel** [comment]
Indeed, I see. Strange, `git pull` didn't see any new changes (and one way or another my browser showed an old instance of the repo on Github, or I was just too tired). Anyway, cloned the repo again, built it, and everything seems to work again. Thanks!

**Comment by marijnh** [comment]
Great! I just rebuilt the main website and that went well too.
