### ISSUE TITLE
Dino demo is broken

### ISSUE THREAD

**Issue by jeremiak** [ProseMirror/website#7]
Hey friends, looks like the dino demo is broken if one is using the latest `master` from `prosemirror/ProseMirror`. I cloned the repo and ran through the installation scripts but when I try and load the page at `/demo_dino.html` I just get the regular ProseMirror instance without the dino button on the menu bar:

![](https://s3.amazonaws.com/f.cl.ly/items/2k2L2l2b3A0R1P0O1o2E/Screen%20Shot%202015-11-23%20at%201.04.36%20PM.png)

I ran into this problem because I was trying to use the demo as a stand in for the documentation around extending the document model, but couldn't get it to work. I then tried to rebuild this demo, but couldn't get that to work either.

**Comment by marijnh** [comment]
Everything should work again. I let the demos lag behind the master branch API a bit now and then to be able to focus on developing without constantly going back to the demos, but I guess that does create confusion if you're trying to use the demos as examples (which is how I actively advertise them).

**Comment by sielay** [comment]
I think it is broken again. There are number of issues (like now library expect src in images), throws some bind related error and don't register option in insert menu.

**Comment by marijnh** [comment]
[The page](http://prosemirror.net/demo/dino.html) seems to be working for me.

**Comment by sielay** [comment]
Example on page might, but when I checkout current version and rebuild it I have errors mentioned. Is page really using 0.1.1 (and hasn't it changed)? I literally copied your DOM and your JS.

**Comment by marijnh** [comment]
Ah, no, the demo is actually lying in its package.json, and is tracking the git master branch.

**Comment by sielay** [comment]
So feature wise it's better (but less safe?) to use master rather than 0.1.1?

**Comment by marijnh** [comment]
Depends on whether you want a stable API or immediate access to bugfixes. I will release another version to npm this week, and will generally try to keep it from falling far behind the repository.

**Comment by sielay** [comment]
Cheers, well we build app using it as we love your `shadow-dom` storage and way editor cleans content. I think I will stabilise it against specific commit and this way control updates.
