### ISSUE TITLE
Markdown Example Link Problem

### ISSUE THREAD

**Issue by amkgo** [ProseMirror/website#76]
In the [markdown example](http://prosemirror.net/examples/markdown/), when I add a link to the last word of the WYSIWYM editor, the link will expand whenever I type other words.

The editor at the home page works well when add the link to the last word.

Andrew

**Comment by marijnh** [comment]
The Markdown schema wasn't setting the `inclusive: false` property on link marks. prosemirror-markdown 1.0.1 should fix that.
