### ISSUE TITLE
Document some ways how to store the state into the database and restore it

### ISSUE THREAD

**Issue by mitar** [ProseMirror/website#79]
Guide is great. But after reading through it I still feel I do not understand what is necessary to store into a database to be able to restore the editor between sessions, and where I get this and how  restore it. I see `toJSON` method on state, for example.

Moreover, in collab example this is even more through. If I have authority full of steps and I am loading an editor to continue working from existing steps, how I initialize the state/steps/collab plugin properly.

**Comment by marijnh** [comment]
> I see toJSON method on state, for example.

Yes, that's what you could use to get a serialized version of the stat to store somewhere.

> If I have authority full of steps and I am loading an editor to continue working from existing steps, how I initialize the state/steps/collab plugin properly.

Make sure the `version` option you pass to the collab plugin matches the version your authority assigns to the document it is initialized with.

**Comment by mitar** [comment]
I opened the issue because I though I would share what I perceived a missing point in the guide and encourage expanding the guide.

Thanks for the input though. I think I know how to use `toJSON`, and probably the idea is that instead of calling `EditorState.create` I would call `fromJSON` to get state instance. What is confusing is how does state interact with steps found in authority. Do I have to reply the steps, or do I just continue from steps after the state's current version. And what is proposed way/time to store state. If I am sending steps to authority, when should I send the state so that next time I do not have to reply all steps.

**Comment by marijnh** [comment]
I think these are questions that can't be answered in a one-size-fits-all way, and people writing a collab editing service won't be able to avoid building up an understanding of the underlying model.

**Comment by mitar** [comment]
Exactly, this is why it is a hard thing to understand and having some guidance would be very helpful. Some best practices, pros and cons, things to consider. I understand there is no one-size-fits-all approach, but there are some common things people want to do and telling what we should keep in mind would be really helpful. For example, when should one be storing `doc` into a database over the whole `state`? And `state` with plugins or without? Even just mentioning that those options exist, and that one can store state with plugins or without is not obvious unless you go and read reference documentation. So having some guidance here in the guide would really make it a bit easier to handle the question: "OK, I got this to run on the client, how to connect this to the server now". I understand that there are so many things possible on the server so it is hard to make an example which would work for everyone, but I am not even asking for an example, maybe just few paragraphs of common patterns and common pitfalls.

I am just trying to help here. I will manage somehow. But I am a new to the project and I read everything I could find (except for the whole reference documentation, this is still pending) and I am trying to give feedback back where is a bit missing. I can understand also if you are not thinking this is worthwhile, but I think it would be really useful.

I will not push back anymore.
