### ISSUE TITLE
Collab demo and embedded code editor examples are broken in IE

### ISSUE THREAD

**Issue by jakeknerr** [ProseMirror/website#87]
Quick heads up that for IE11, the Collaborative editing demo throws a `'Promise' is undefined` error and the Embedded Code Editor example throws a `Object doesn't support property or method 'assign'` error.

A quick and simple solution could be adding a polyfill service like ```<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>``` to these examples.

**Comment by marijnh** [comment]
Thanks for the suggestion. Attached patch seems to help.
