### ISSUE TITLE
Keyboard commands in schema example conflict with system behavior

### ISSUE THREAD

**Issue by etherbob** [ProseMirror/website#89]
Some of the keyboard commands in the [Schemas from scratch](http://prosemirror.net/examples/schema/) example conflict with existing macOS system shortcuts (CMD-space triggers spotlight, CMD-q quits the current application, etc). These sorts of challenges trip me up in general so I have no clue what a better set would be, but it might be worth tweaking to avoid having a reader accidentally quit their browser.

**Comment by marijnh** [comment]
Good point. Attached patch moves the demo to use ctrl on all platforms.
