### ISSUE TITLE
Include commit for prosemirror dependency

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#9]
The make command is failing because of changes to the ProseMirror API.

Can we tie the `prosemirror` dependency to a commit? That way the API can continue to change and guarantee the website will work. When the website should get an updated version of ProseMirror, the package dependency can be updated.

**Comment by marijnh** [comment]
I am planning to tag the first version this or next week, at which point I'll start depending on specific versions (and documenting breaking changes). Do you think you can hold out until then? (Why are you running this code locally anyway? As example?)

**Comment by ericandrewlewis** [comment]
> I am planning to tag the first version this or next week, at which point I'll start depending on specific versions (and documenting breaking changes). Do you think you can hold out until then? 

Totally :smiley: 

> (Why are you running this code locally anyway? As example?)

Using the dino example as boilerplate to fool around with the custom node type API as it is now.

**Comment by ericandrewlewis** [comment]
Fixed in 7650385935a1fcc3064fa0f6fcc02949565bf9b1
