### ISSUE TITLE
Suggest Small Change to Reference Guide For Node#inlineContent

### ISSUE THREAD

**Issue by jakeknerr** [ProseMirror/website#92]
Currently, the reference guide describes ```Node#inlineContent``` as
"True when this node **has** inline content."

I suggest it be changed to "True when this node **allows** inline content".  "True when this node **accepts** inline content" could also work.

The reason I suggest the change is because ```node.inlineContent``` can be ```true``` even it is does not have any content.  The way I read the original description is that the node must have content to have a ```true``` value for the ```inlineContent``` property, when it fact it can be empty and still return a ```true``` value.

A minor suggestion, but it has confused me a few times now.  What do you think?

**Comment by marijnh** [comment]
Sounds good. Want to submit a pull request?

**Comment by jakeknerr** [comment]
Done in prosemirror-model.
