### ISSUE TITLE
Invalid link to source code

### ISSUE THREAD

**Issue by mitar** [ProseMirror/website#93]
At least on [this page](https://prosemirror.net/examples/track/):

> This page won't list the whole source code for the example, only the most interesting parts.

Points to:

https://github.com/ProseMirror/website/blob/master/pages/examples/track/example.js

But it should to:

https://github.com/ProseMirror/website/blob/master/example/track/index.js

**Comment by marijnh** [comment]
Thanks for noticing that. Should be fixed now.
